CONTIKI_PROJECT = button-hal-example
CONTIKI = ../../..

all: $(CONTIKI_PROJECT)

PLATFORMS_ONLY = cc26x0-cc13x0 cc2538dk openmote-cc2538 zoul native simplelink efr32tb

include $(CONTIKI)/Makefile.include
