/*
 * Board definition header for the Seeed Studio XIAO nRF54L15.
 * Mirrors the structure used by other nRF boards.
 */
#ifndef XIAO_NRF54L15_DEF_H_
#define XIAO_NRF54L15_DEF_H_

#define XIAO_NRF54L15_LED_PORT       2
#define XIAO_NRF54L15_LED_PIN        0

#define XIAO_NRF54L15_BUTTON_PORT    0
#define XIAO_NRF54L15_BUTTON_PIN     0

#define XIAO_NRF54L15_UART_INSTANCE  20 /* UART20 */
#define XIAO_NRF54L15_UART_TX_PORT   1
#define XIAO_NRF54L15_UART_TX_PIN    9
#define XIAO_NRF54L15_UART_RX_PORT   1
#define XIAO_NRF54L15_UART_RX_PIN    8

#define NRF_UARTE_INSTANCE_ID XIAO_NRF54L15_UART_INSTANCE
#define NRF_UARTE_TX_PORT     XIAO_NRF54L15_UART_TX_PORT
#define NRF_UARTE_TX_PIN      XIAO_NRF54L15_UART_TX_PIN
#define NRF_UARTE_RX_PORT     XIAO_NRF54L15_UART_RX_PORT
#define NRF_UARTE_RX_PIN      XIAO_NRF54L15_UART_RX_PIN

#endif /* XIAO_NRF54L15_DEF_H_ */
